name: Python CI

on:
  push:
    branches:
      - main
      - 'feature/*'  # Optional: include other branches you want to trigger the workflow
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # You can choose a different OS, e.g., macos-latest, windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements.txt  # Ensure dependencies are listed in requirements.txt

    - name: Run tests
      run: |
        pytest  
